### ISSUE TITLE
Import manual infrastructure into terraform

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#1360]
Many important corners of our infrastructure are built manually in between terraform steps. To the extent possible, we should eliminate those corners.

This may need to be split into sub-issues, but to start a running list:

- [x] the subnet delegation that makes our app service work is manually created (fix in #1342)
- [x] the private link between our VM subnet and the database is manually created (#2028)
- [x] #2029
- [x] the MFA policy should be attached to the correct group in `global` (fix in #1497)
- [x] #2066
- [x] #2080

**Comment by benwarfield-usds** [comment]
https://github.com/CDCgov/prime-simplereport/pull/1342#issuecomment-822589804 has many more examples.

**Comment by LGFranklin** [comment]
This is a placeholder/ @jdorothy will add more specifics

**Comment by jdorothy** [comment]
@LGFranklin this is updated with the two (new) issues remaining
