### ISSUE TITLE
Update "People" to say "Patients"

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-simplereport#1427]
**Background:**
The earliest designs for SimpleReport used the term "patients", but after doing research with our initial pilot partner and other similar nursing home sites, we learned that they use the term "patients" to specifically mean a resident. Since they were primarily testing staff (but also residents), this was confusing. To alleviate this, we changed the page name to say "People" instead.

**Current issues:**
Over time it has become increasingly difficult to avoid using the word "patient". The word "People" is not as intuitive or clear, leading us to say things like "People who get tested" in order to clarify. This is a mouthful and makes writing guidance more difficult. The word is even harder to avoid when describing what we internally call the "patient experience"—any SimpleReport feature that collects data or sends data to the person being tested. We have also expanded to many other facility types where the resident/patient confusion is not an issue. However, nursing homes still make up a significant percentage of our user base (estimated 20–30% of our organizations)

**Next steps**
Per the decision in the latest style guide, we want to revert back to calling this page and any related features "Patients". We also need to be intentional about how we do this to avoid confusion with our current users and make sure we are not introducing UX issues for nursing homes in particular. In order to do this we need to answer the following questions:

- Is the term "patients" actually confusing for nursing home users, or would they be able to figure it out in context?
- If it is actually confusing, how might we make it clear for new users? Is it enough to update our training videos/documentation, or do we need permanent helper text next to the Patient label? (e.g. “Patients: anyone who gets a test)”
- How might we make the change less jarring for existing users (new feature announcement popover, etc)

**Task checklist**
- [ ] Validation/research w/ users to answer the above questions
- [ ] Update all Figma files to remove references to "people"
- [ ] Create new/updated feature announcement popover design
- [ ] Update UI (People table/profile pages/global nav)
- [ ] Re-record training videos
- [ ] Update user guides on the Resources pages

**Comment by Rebecca-LM** [comment]
Adding @vz3 on here for visibility since it seems we'll need to do some validation/research around this term.

**Comment by vz3** [comment]
Could be good fit for unmoderated/first-click testing

**Comment by LGFranklin** [comment]
7/19 Update: Do some testing of the two terms (and others) to determine if this change needs to be made.

**Comment by Rebecca-LM** [comment]
Created a [running list of content-related stuff ](https://docs.google.com/document/d/1nUAVu_w3S6r57Urb3XWdJV2ci-JzG4_4nuq7veJWn6M/edit)we want to test when we're able.

**Comment by vz3** [comment]
Moving this to in progress bc we had covered this in testing in April and we're also covering this validation right now as a part of analytics research.

**Comment by Rebecca-LM** [comment]
@lauraykerr @vz3 fight the good fight on this one!! :)

**Comment by lauraykerr** [comment]
In-progress audit of where "patient" and "person" appear in app and static site: https://docs.google.com/spreadsheets/d/12zkWLB9Yjg4igvD0wVVu4yVnPMoSEpxyLSLgVNyaOuU/edit?usp=sharing

**Comment by emmastephenson** [comment]
Request: change across the board to "patient" or "patients" for all the locations listed in the spreadsheet above.

**Comment by emyl3** [comment]
@lauraykerr want to double check this is ready for dev work right?

**Comment by emyl3** [comment]
@lauraykerr want to double check this is ready for dev work right?
