### ISSUE TITLE
Multiplex

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3410]
### Description
This epic will track the work required to implement Multiplex testing.

### Additional context
[Figma](https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=6364%3A25128) (not final)
[Research plan](https://docs.google.com/document/d/1qYS7GXnA7XR7OHB3i3NnFt14qiYSaV0cPzLR7Hhxrzs/edit?usp=sharing)
[Engineering architecture doc](https://docs.google.com/document/d/11QpgPUGDM1HTqHEjae7roeJaynkcJ_15MoQ8jGaTphs/edit?usp=sharing)

### Acceptance Criteria for Epic

- [ ] Users can submit multiplex tests
- [ ] Users can view the outcomes of all results on a multiplex test
- [ ] Patients can see all results from a multiplex test through the patient experience

### Master plan
This is also in the eng doc, but pasting here for easier access.

#### Database Changes

- Add a new table with diseases and their potential results, using the LIVD table as a guide. For now, this table only needs to include COVID-19, Flu A, and Flu B. We can store potential results as JSON. (#3411)
- Add a new column on the device table to record supported diseases. This will likely be a list or some other data structure that supports multiple entries. (#3412)
- Add a new table to enumerate potential results. For now, this table will have columns of internal_id, covid_result, flu_a_result, and flu_b_result. (As we add further diseases, this table will expand.) The rows in the database will correspond to potential result combinations, stored as LOINC codes. We don’t need to populate this table immediately; we can do so in code as results are generated. (#3420)
- Change the type of the results column on test events and orders from an enum to a UUID. This UUID will point to the internal id of the potential results table above. (#3421)
- Once all the new columns are in place, backfill existing devices and test orders/events to mark them as COVID-19 results. It may be possible to backfill some with a default value instead of a separate SQL execution. 

#### Backend Changes
- Update all the database models and service calls to reflect the new database columns
    - Update the type of [TestResult.java](https://github.com/CDCgov/prime-simplereport/blob/4808c09da2db80d747868a74f4940e9d20f9d31e/backend/src/main/java/gov/cdc/usds/simplereport/db/model/auxiliary/TestResult.java) from an enum to a database model class that reflects the new table (#3421)
    - Update the type of the result column in [TestEvent.java](https://github.com/CDCgov/prime-simplereport/blob/main/backend/src/main/java/gov/cdc/usds/simplereport/db/model/TestEvent.java) and [TestOrder.java](https://github.com/CDCgov/prime-simplereport/blob/4808c09da2db80d747868a74f4940e9d20f9d31e/backend/src/main/java/gov/cdc/usds/simplereport/db/model/TestOrder.java) to be a UUID (it’s currently a custom enum) (#3421)
    - Add a new database model class for the supported diseases table (#3430)
    - Add a new supported diseases column to [DeviceType.java](https://github.com/CDCgov/prime-simplereport/blob/4808c09da2db80d747868a74f4940e9d20f9d31e/backend/src/main/java/gov/cdc/usds/simplereport/db/model/DeviceType.java) (#3431)
    - Add some kind of translation class for LOINC codes to display names (#3432)
- Once our LIVD-backed disease table is in place, begin reading from ReportStream’s LIVD API to update the table. (#3433)
    - Once the API calls are in place, set up a daily job to read from the API and update the table accordingly. (#3434)
- Filter our ReportStream sending logic to only pass along COVID-19 test results from TestEvents (#3435)
- Update the patient link to show multiple results from the same test order, not just COVID-19
- (Depending on frontend changes) update mutations to pass multiplex results from the backend
- (Depending on frontend changes) update mutations to read multiplex results from the database when necessary. 

#### Frontend Changes
- These will largely depend on the frontend designs, which have not yet been finalized. It’s safe to assume that we’ll need to update the test cards, results tab, and patient results view to support multiplex testing.

**Comment by emmastephenson** [comment]
Done, has been done for a while now! Multiplex is in prod and we have several thousand flu results reported.
