### ISSUE TITLE
SimpleReport can have 2+ organizations

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#405]
We want to onboard more organizations. 

The API needs to be able to handle users from multiple organizations!

Deployment TODO:
- [x] deploy updated code in single-tenant mode to `dev` 
- [x] deploy updated code in no-security mode to `demo` 
- [x] validate single-tenant mode in `dev`
- [x] deploy updated code in single-tenant mode to `prod` 
- [x] validate single-tenant mode in `prod`
- [x] update Okta settings for `dev` environment
- [x] rename Okta groups for `dev` environment
- [x] update Okta settings for `stg` environment
- [x] create Okta groups for `stg` environment
- [x] update login links in `dev` and `stg`  (CDCGov/SimpleReport_Public_Site#44)
- [x] redeploy `dev` in multi-tenant mode and validate (#508)
- [ ] redeploy `stg` in multi-tenant mode and validate 
- [x] update Okta settings in production
- [x] create Okta groups in production
- [x] update login link in production (CDCgov/SimpleReport_Public_Site#48files)
- [ ] release production in multi-tenant mode (and validate!!!)

**Comment by benwarfield-usds** [comment]
This is our first run of getting more information than "who is this?" out of our IDP, so it needs to put us on the right path for the future.

Short term:
* we need Okta to tell us what organization the current user belongs to, if any
* we need Okta to tell us if the current user is a superuser (site admin—for access to device types, swabs, and organization creation).
* if neither of those things is true, the user will be unable to do anything at all: we should probably have a way of communicating that to them through the UI, in case of mis-configuration

Medium to long term:
* we need Okta to tell us what roles a user has in their organization
* we need Okta to tell us what facilities a user is authorized to work at
* we need users to be able to identify the users (actual or potential) who are members of an organization, and in some cases to see what roles they have and facilities they are authorized for
* we need users with the correct role to be able to _grant and remove_ roles on other users, and invite new users to the application

Okta has APIs that should allow us to do each of these things, in one of two ways:
* we could have the users be authenticated for Okta themselves, and then either
  * make API calls on their behalf 
  * or have them make API calls directly from the client
* we could have the users be authenticated just to our app, and have our application have its own access credentials for Okta, which have the privileges we need for our user-facing operations.

The first one seems logical but introduces a bunch of complexity: we probably want to do the second one, at least for now. (This also allows us keep all our IDP interactions encapsulated, so if we ever change to a different IDP, we won't have to change every layer of the code.)

**Comment by benwarfield-usds** [comment]
Additional somewhat tangential practical considerations:
* we have only one directory in Okta: we should take steps to make sure people are not accidentally granted production access when we meant them to have staging or demo access, or vise-versa.
* if you are validly signed in on Okta but have no organization assigned, we will probably send a pretty nasty message to the client under most circumstances. The client should be prepared to tell people why this is happening.

**Comment by benwarfield-usds** [comment]
Final pragmatic consideration: we probably will share our directory with Data Hub, which will have its own user groups. If we have a large number of prefixed groups, we should include a common prefix (e.g. `SR-` to indicate that they are SimpleReport's user groups.

**Comment by benwarfield-usds** [comment]
And with that, the deceptively-simple plan for using Okta groups to handle our roles:

## Groups 
* since we may share our group list with other applications, all groups intended exclusively for SimpleReport will have the prefix `SR-`.
* every group will have one of (initially) three subsequent fragments: `PROD-`, `STG-` or `TEST-`. to indicate the environment it applies to.
* the next segment will either be a global role (e.g. `ADMIN` or `SUPERUSER`, though the former seems better to me) or a tenant-scoped role with the following three parts:
  * the word `TENANT`, followed by `:`
  * a string purporting to be the external ID of a tenant organization that exists (or will exist, or used to exist) in this environment (e.g. `myfriendlylongtermcare.org`), followed by `:`
  * the name of a tenant-scoped role (e.g. `USER`, `ADMIN`)

Each Java instance will know the name of the admin group for the environment in which it is running, and be able to decode tenant-level groups to produce tenant-level authorizations.

## Claims and scopes

We will configure Okta to have one groups claim for each environment, which will return all groups with the prefix `SR-${ENV}-`. The Okta Spring Security configuration will be told to point to the correct claim for the current environment (with any luck, the other claims won't be there at all).

**Comment by benwarfield-usds** [comment]
This is marked closed because the last change was pushed, but we still need to release to prod and double check that people can still log in.

**Comment by benwarfield-usds** [comment]
Actually done now.
