### ISSUE TITLE
EPIC: Allow users to make corrections to test results after they have been submitted

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-simplereport#473]
- [ ] In the results table there should be an Action menu with the following options:
- View Details (moved to https://github.com/CDCgov/prime-simplereport/issues/490)
- Make Correction (moved to https://github.com/CDCgov/prime-simplereport/issues/491)
- Print Results (printing is a separate ticket https://github.com/CDCgov/prime-simplereport/issues/426)
<img width="920" alt="Screen Shot 2021-01-05 at 11 03 57 AM" src="https://user-images.githubusercontent.com/60664222/103669024-d7fdbc00-4f45-11eb-899c-761b7ad177f7.png">

- [ ] Clicking "View Details" from the action menu should open a test results details screen. If there have been no corrections made, the default view should look like this:
<img width="707" alt="Screen Shot 2021-01-05 at 11 05 17 AM" src="https://user-images.githubusercontent.com/60664222/103669161-ffed1f80-4f45-11eb-838f-7283d1f8643b.png">

- [ ] Clicking "Make Correction" either from the "View Details" modal or from the original Actions menu, should open the test details into an edit mode.
<img width="708" alt="Screen Shot 2021-01-05 at 11 10 21 AM" src="https://user-images.githubusercontent.com/60664222/103669670-a6d1bb80-4f46-11eb-8a41-eb483cd0aaa4.png">

- [ ] Selecting the "Mark entire result as an error" checkbox crosses out the original results details. This option would most likely be used if the result was submitted for the wrong person and the user wanted to essentially "delete" the result (but you can't really delete so we say Mark as error instead)
<img width="711" alt="Screen Shot 2021-01-05 at 11 10 57 AM" src="https://user-images.githubusercontent.com/60664222/103669795-cd8ff200-4f46-11eb-878a-b3c054a7d827.png">

- [ ] After submitting a correction, users should see a success message toaster notification
<img width="736" alt="Screen Shot 2021-01-05 at 11 14 17 AM" src="https://user-images.githubusercontent.com/60664222/103670142-337c7980-4f47-11eb-9442-39f11bd2083b.png">

- [ ] After submitting a correction, the modal should go back to the "view details" read only mode. The corrected detail should display the original content grayed and crossed out in the same row, and the correction history should display as a timeline on the left. Below the test details should display who the correction was submitted by, the reason, and the date/time of the correction.
<img width="684" alt="Screen Shot 2021-01-05 at 11 13 44 AM" src="https://user-images.githubusercontent.com/60664222/103670289-6292eb00-4f47-11eb-8006-39fd5ebffabf.png">

- [ ] Clicking in the timeline to see the original result should show you what the result looked like at that point in time, and have an "Original Result" tag 
<img width="594" alt="Screen Shot 2021-01-05 at 11 16 51 AM" src="https://user-images.githubusercontent.com/60664222/103670486-a128a580-4f47-11eb-882c-c6e91bf2f398.png">

- [ ] If the correction was to mark the result as an error, then this is what it should look like when submitted
<img width="611" alt="Screen Shot 2021-01-05 at 11 21 30 AM" src="https://user-images.githubusercontent.com/60664222/103670887-2f9d2700-4f48-11eb-8de8-2aa95cf5c46e.png">

**Comment by timothybest-usds** [comment]
I broke this ticket up into multiple tickets for execution. New tickets are noted in the description
