### ISSUE TITLE
Add details view to test results page

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#490]
## TODOS
Implement v1 of details view (done)
- [x] Add dropdown to Test Results table (also needed in https://github.com/CDCgov/prime-simplereport/issues/426)
- [x] add "Mark as Error" link with an alert to confirm
- [x] add reason for error
- [x] cross off the test result if there is an error

Implement v2 of details view (see screenshots below or [engineering prototype](https://www.figma.com/proto/CEzBM8kUw8LyWdfAhUThYb/Engineering-Ready-Prototype?node-id=23%3A260&scaling=scale-down&page-id=0%3A1))
- [x] Add a “View details” option to actions menu
- [x] Add details view UI 
- [x] In the details view, if the result is marked an error, show all text as grey with a strike through

## Mocks/Specs: 
https://docs.google.com/document/d/1qqv4kH0sb865NYdk6rpnU9cQMWlu6mFHK2J8CsQOmOA/edit#

Add "View details" option to action menu
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/d07a3920-607f-4503-8516-1b438c4c3094)

Add details view UI
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/9a02a884-203a-487c-ab4b-f11c29beddd6)

Details UI if result has been marked an error
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/70f115ea-6a6a-45d3-bbc9-689ea5282b6f)

## Ref
EPIC: https://github.com/CDCgov/prime-simplereport/issues/473
