### ISSUE TITLE
Q1 Accessibility Audit

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4955]
### Background
We need to check on accessibility and make sure there are no regressions since the summer 2022 audit.

### Action Requested
Conduct Axe accessibility audit on a prodlike environment (staging, or a `dev` environment with a fresh cut of main). This entails running both manual and automated scans on the following pages/flows:

1. Static site

- [x] Static site homepage
- [x] Static site support homepage
- [x] Static site generated page (a sample help page like password reset)

2. Admin pages

- [x] Sign up flow (simplereport.gov/signup)
- [x] Add/edit facility
- [x] Manage facilities
- [x] Manage users 
- [x] Patient self-registration settings (https://demo.simplereport.gov/app/settings/self-registration)

3. Standard user pages

- [ ] Dashboard
- [ ] Conduct test (with at least 2 tests active)
- [ ] Results
- [ ] Person
- [ ] Add/edit person form
- [ ] User account creation (password/MFA setup)
- [ ] Results bulk upload
- [ ] Patient bulk upload

4. Patient experience

- [ ] Patient self-registration
- [ ] Results view

5. Superadmin experience

- [ ] Organization verification
- [ ] Add/edit device
- [ ] Tenant data access

### Acceptance Criteria
Manual and automated tests have been run on all of the above pages, and tickets have been created for any new issues.

### Additional information
[Spreadsheet template](https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/Shared%20Documents/Accessibility%20SOP/Sample%20Accessibility%20Audit%20-%20MAKE%20A%20COPY.xlsx?d=wf8239a7e76034fe88ec5409e3367333e&csf=1&web=1&e=hfWi3d)
[Main site audit summer 2022](https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20SimpleReport/Accessibility/Main%20Site%20Audit.xlsx?d=w43efe529da074d2fbc405db66f45d749&csf=1&web=1&e=nAzGBB)

**Comment by emmastephenson** [comment]
1/5/23 update: Static site tested; no issues found.

**Comment by emmastephenson** [comment]
Tracking sheet, if necessary: https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20SimpleReport/Accessibility/Q1%202023%20Accessibility%20Audit.xlsx?d=w43ca71d957e84f729c4aba11873d4a52&csf=1&web=1&e=e10lq4

**Comment by emmastephenson** [comment]
@emmastephenson to create new tickets to track accessibility training for the following folks:
- @BobanL 
- @johanna-skylight 
- @lauraykerr 
- @kenieh 
- @tomiobikunle

**Comment by emmastephenson** [comment]
@emmastephenson to convert this to epic and break into smaller tickets

**Comment by emyl3** [comment]
I'll start on the "2. Admin pages" items in the meantime! :)

**Comment by emyl3** [comment]
For "running both manual and automated scans"
With the axe dev tool
![Screen Shot 2023-01-11 at 13.10.41.png](https://images.zenhubusercontent.com/5ffc8b9b4950f50bf5829d88/370bbe1c-911b-497b-91bd-5a7a915c3e3f)

- Run either "Scan ALL of my page" or "Scan PART of my page" as needed
- Then go through the appropriate "Start an Intelligent Guided Test" options (For example, some pages may not need "Forms" for example if there are no forms on that page)
