### ISSUE TITLE
Patient Time of Test Questions- V1

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#505]
As a patient, I would like to answer questions related to my COVID-19 test myself, so they are submitted privately.

As a test administrator, I would like patients to answer their own time of test questions, so that I don't have to do it and I don't have to ask my co-workers and other patients awkward questions like "are you pregnant?"

This story depends on the completion of #560 

**Definition of Done**
- [x] Wire up the front end and back end 
- [x] Add ETE tests for this flow

**Success Criteria**
- [x] Questions can be answered by a patient, and match the time of test questions in SimpleReport
- [x] View is mobile optimized and matches the design
- [x] Data can be submitted to SimpleReport

**Comment by nullflux** [comment]
### Questions (answered)
- Is it feasible to use this react app?
  - **Yes**
- Is it OK not to have an edit feature in the confirm personal details page (for this sprint)?
  - **Yes, example text: "Confirm if this is correct and tell the testing administrator if it's incorrect."**

**Comment by maya** [comment]
@aliciabeckett-gov is this epic is for the basic flow added in #641 or does it also include edit patient info and add new user features?

**Comment by aliciabeckett-gov** [comment]
This is for the basic flow added in #641 @maya

**Comment by maya** [comment]
@aliciabeckett-gov thanks, if that's the case, can this be closed?
