### ISSUE TITLE
Send patient links via text

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#506]
As a patient, I can access the SimpleReport patient app, so that I can submit data for my COVID-19 test.

- [ ] Test administrator can send a text to the patient
- [ ] Patient Receives a text message
- [ ] Text message has a unique link that expires, and takes them to the patient experience

**Comment by maya** [comment]
Can you share the Figma designs for the text messaging flow? @katiealoisi @hmyers-cms

**Comment by katiealoisi** [comment]
Yup, they are [here](https://www.figma.com/file/VGBQmqKMTjO1tdYTCpzwcd/Design-WIP?node-id=2507%3A31813) in the Archive section of the Figma file. Note this includes the email option, so please ignore that. @maya

**Comment by maya** [comment]
Thanks, @katiealoisi. Are we removing the QR code option or keeping it?

**Comment by maya** [comment]
@aliciabeckett-gov would like to know your thoughts on this as well.

**Comment by aliciabeckett-gov** [comment]
I think it could be interesting to let users have both options and see what they do. Ultimately we should look at the data and if everyone is opting for text messaging the remove the QR code. On the other hand, it can be hard to take things away from users.

I also wonder if we could add the text option/QR code to the existing time of test popup so we remove the extra click with the new modal.

@katiealoisi @hmyers-cms @maya what are your thoughts?

**Comment by katiealoisi** [comment]
I'd advocate to keep it simple and roll out with the text option (no QR code), especially since it's more secure and users said they wanted it. If we see a need for the QR code, we can always introduce it later? 

As far as keeping the TOT exposed and adding the text option to the same screen, I worry that the UI will be cluttered and potentially not as clear to users. It could make sense to keep the TOT Qs exposed if we want that to be the default path or think it might be the default path, but this will likely be different depending on the site so I don't think we should encourage one option over another until we know more. We can definitely keep an eye out for this during the beta testing period though.

**Comment by nullflux** [comment]
Removed "New Patient Registration" from this epic; closing the epic.
