### ISSUE TITLE
P2: Improve Test Results Table columns and design

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#513]
- [x] Add date of birth to table
- [x] Remove "Unique ID" (also in https://github.com/CDCgov/prime-simplereport/issues/290)
- [x] Update data format from `Jan 5, 2021 2:27 PM` to `01/05/2020 1:15pm` (captured in https://github.com/CDCgov/prime-simplereport/issues/350)
- [x] Map Result display values
```
"POSITIVE" -> "Positive"
"NEGATIVE" -> "Negative"
"UNDETERMINED" -> "Inconclusive"      
```
- [x] Add column for Symptoms "Yes"/"No" value
- [x] Add column for Submitter (Depends on: https://github.com/CDCgov/prime-simplereport/issues/514)
Mock:
![Screen Shot 2021-01-08 at 11 40 06 AM](https://user-images.githubusercontent.com/53869143/104040949-480a7d00-51a6-11eb-843e-5b2eb8042eb1.png)

- [x] Update "Date of Test" to "Test date"
- [x] Update "Person Name" to "Person"
