### ISSUE TITLE
V2 Data upload (Allow Horizontal Scaling)

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#667]
Priorities:

1. Be able to run simplereport.gov on 2 machines and only have one upload per day
2. Upload should run multiple times a day
3. The upload should run on a machine that isn't the web server
4. Mechanism for retrying failed uploads
5. Mechanism for correcting records that fail to upload due to bad data

Spec: https://docs.google.com/document/d/129PINU3xTXDzZ5q4lUZdmlDUGOC_WUY0-fcii-9kino/edit#

**Comment by TomNUSDS** [comment]
For very short-term fixes to just get us a few more weeks:
- [ ] Change CRON string to run more than once-per-day, but use specific times.
- [ ] Talk to Datahub team to figure out "daily maintenance windows" where they know we won't be uploading.
- [ ] Add @benwarfield-usds postgres table locking for the `data_hub_upload`. This should allow multiple instances to run and not bump into each other if they are all using the same CRON string and clocks are synced.
- [ ] Don't report empty uploads to the Slack monitoring channel otherwise it will be too noisy.

**Comment by benwarfield-usds** [comment]
I disagree with bullet 3, FWIW—absent some impact on performance for the client, we should keep it all on one app server to minimize the number of things that can break.

**Comment by TomNUSDS** [comment]
Bullet 3 is maybe poorly worded. I think it means what you've done with #756 but we just need to remember the mutex locking only works if all the machines try to upload at the same time (e.g. scheduled times versus delta times).
