### ISSUE TITLE
Preparation for Scaling

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#722]
Spec: https://docs.google.com/document/d/1AcC878e2IyubfAZacxlq89WWcmMcZeDH6uN5hrdBwwc/edit#heading=h.2jmb9cuu3v1h

P1
- [x] ~~[n+1 query of patients](https://app.zenhub.com/workspace/o/cdcgov/prime-simplereport/issues/729)~~ solved with pagination

P2
- [ ] [move patient search to backend for test queue](https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/740)
- [x] [v1 pagination of people tab](https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/747)

P3
- [x] [Test Queue polls to much](https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/713)
- [ ] [n+1 query problem on test queue](https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/759)
- [ ] Address validation
