### ISSUE TITLE
Add Org Type, and bring back Lookup ID as Student/Staff ID for schools

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#834]
As a school, I want to be able to look up students using their student ID so that they are easier to find and I can join the SimpleReport data with my other data about them.

**Description**
As a part of https://github.com/CDCgov/prime-simplereport/issues/290 we removed the Lookup ID because it was confusing, no one used it, and we were worried users would put SSNs in there. However, we've gotten strong feedback from universities and K12 schools that they would really like to use it to be able to lookup students by their ID and to join SimpleReport data to their other data.

No other user type has expressed interest in using this field. Rather than have it generic and available to everyone, instead we will only make it available to schools.

**TODO:**

- [ ] Create an Organization Type field on the Organization settings page with options: K12 School, University, Nursing Home, Assisted Living, Urgent Care/ER, Clinic, Mobile Testing Site, Group Home, Other Congregate Setting, Other
- [ ] If the Organization type is K12 school or University- show the lookup ID field. 
- [ ] Change the Lookup ID label to say "Student/Staff ID"

**Comment by benwarfield-usds** [comment]
From an implementation side it seems like an organization preference that we're setting implicitly when we set the org type. That seems fine from a UX standpoint, but probably we should make the API more explicit.

**Comment by nullflux** [comment]
We did this for student ID... #1170 & its PR #1213. Are we looking to add Staff ID at this time, or is this ticket just mispaced?
